// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// calculateLocAve
List calculateLocAve(List nonzeroc, List nonzerog, NumericVector r, NumericVector h);
RcppExport SEXP _scKWARN_calculateLocAve(SEXP nonzerocSEXP, SEXP nonzerogSEXP, SEXP rSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type nonzeroc(nonzerocSEXP);
    Rcpp::traits::input_parameter< List >::type nonzerog(nonzerogSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type r(rSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type h(hSEXP);
    rcpp_result_gen = Rcpp::wrap(calculateLocAve(nonzeroc, nonzerog, r, h));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_scKWARN_calculateLocAve", (DL_FUNC) &_scKWARN_calculateLocAve, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_scKWARN(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
